image: node:lts-alpine

variables:
  DB_URI: bolt://x2021visualit2003257697000.northeurope.cloudapp.azure.com:7688
  LOGS_URI: mongodb+srv://visualit:MsUgkkdNK2vfHUKd@cluster0-fwt6p.mongodb.net/test?retryWrites=true&w=majority

stages:
  - build
  - test
  - auto_increment

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - wget --spider -q http://x2021visualit2003257697000.northeurope.cloudapp.azure.com:3001/
    - npm start &
    - sleep 2
    - npm test

auto_increment:
  stage: auto_increment
  before_script:
    - apk add --update curl jq
  script:
    - "chmod +x versioning/auto_increment.sh"
    - "./versioning/auto_increment.sh versioning/VERSION_FILE ${CI_PROJECT_URL} ${API_ACCESS_TOKEN} ${CI_PROJECT_ID}"
