image: node:10

variables:
  DB_URI: bolt://x2021visualit2003257697000.northeurope.cloudapp.azure.com:7688
  LOGS_URI: mongodb+srv://visualit:MsUgkkdNK2vfHUKd@cluster0-fwt6p.mongodb.net/test?retryWrites=true&w=majority

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - wget --spider -q http://x2021visualit2003257697000.northeurope.cloudapp.azure.com:3001/
    - npm start &
    - npm test
