image: node:lts-alpine

variables:
  DB_URI: bolt://x2021visualit2003257697000.northeurope.cloudapp.azure.com:7688
  LOGS_URI: mongodb+srv://visualit:MsUgkkdNK2vfHUKd@cluster0-fwt6p.mongodb.net/test?retryWrites=true&w=majority

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - wget --spider -q http://x2021visualit2003257697000.northeurope.cloudapp.azure.com:3001/
    - npm start &
    - sleep 2
    - npm test

deploy:
  image: docker:19.03.12
  stage: deploy
  only:
    refs:
      - master
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/visualitgroup/api/server:latest .
    - docker push $CI_REGISTRY/visualitgroup/api/server:latest
