version: '2.1'

services:
  api:
    image: api
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - 3000:3000
      - 8087:8087
      - 8088:8088
