version: '2.1'

services:
  api:
    image: api
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    links:
      - graph
      - logs
    depends_on:
      - logs
      - graph
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - 3000:3000
    environment:
      - DB_URI="bolt://graph:7687"
      - LOGS_URI=mongodb://visualit:password@logs:27017/visualit
  graph:
    image: neo4j:3.5
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./graph/data:/data
      - ./graph/logs:/logs
      - ./graph/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
  logs:
      image: mongo:latest
      environment:
        - MONGO_INITDB_DATABASE=visualit
        - MONGO_INITDB_ROOT_USERNAME=visualit
        - MONGO_INITDB_ROOT_PASSWORD=password
      ports:
        - 27017:27017
      volumes:
        - ./logs/data:/data/db
        - ./logs/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
